name: Run tests

on:
  push:
    branches: [ main, '[0-9]*.[0-9]*.x' ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main, '[0-9]*.[0-9]*.x' ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Execute check without tests
        run: ./gradlew check -x test
  test:
    name: Testing on JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build
        run: ./gradlew build -x test
      - name: Execute tests
        run: ./gradlew test -x :fixture-monkey-tests:doc-examples:java-examples:test -x :fixture-monkey-tests:doc-examples:kotlin-examples:test
        env:
          CI: Github Action

      - name: Publish test report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          check_name: JUnit Test Report on JDK ${{ matrix.java }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true

      - name: Test Summary
        uses: actions/upload-artifact@v4  # upload test results
        if: always()
        with:
          name: test-results-jdk-${{ matrix.java }}
          path: '**/build/test-results/test/TEST-*.xml'
